-- ZXAItext MySQL 8 initialization SQL
-- This file is generated from the final Django model state, not replayed historical migrations.
-- Import command example: mysql -uroot -p2005120600 < init.sql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE IF NOT EXISTS `ZXAItext` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ZXAItext`;

DROP TABLE IF EXISTS `django_migrations`;
DROP TABLE IF EXISTS `security_findings`;
DROP TABLE IF EXISTS `security_scan_tasks`;
DROP TABLE IF EXISTS `performance_load_test_tasks`;
DROP TABLE IF EXISTS `data_factory_record`;
DROP TABLE IF EXISTS `unified_notification_configs`;
DROP TABLE IF EXISTS `app_virtual_device_pool`;
DROP TABLE IF EXISTS `app_virtual_devices`;
DROP TABLE IF EXISTS `app_notification_logs`;
DROP TABLE IF EXISTS `app_scheduled_tasks`;
DROP TABLE IF EXISTS `app_test_executions`;
DROP TABLE IF EXISTS `app_test_cases`;
DROP TABLE IF EXISTS `app_test_suite_cases`;
DROP TABLE IF EXISTS `app_test_suites`;
DROP TABLE IF EXISTS `app_packages`;
DROP TABLE IF EXISTS `app_component_packages`;
DROP TABLE IF EXISTS `app_custom_components`;
DROP TABLE IF EXISTS `app_components`;
DROP TABLE IF EXISTS `app_elements`;
DROP TABLE IF EXISTS `app_devices`;
DROP TABLE IF EXISTS `app_test_config`;
DROP TABLE IF EXISTS `app_projects`;
DROP TABLE IF EXISTS `ui_execution_logs`;
DROP TABLE IF EXISTS `ui_execution_evidences`;
DROP TABLE IF EXISTS `ui_execution_steps`;
DROP TABLE IF EXISTS `automation_executions`;
DROP TABLE IF EXISTS `ui_ai_execution_records`;
DROP TABLE IF EXISTS `ui_ai_cases`;
DROP TABLE IF EXISTS `ui_task_notification_settings`;
DROP TABLE IF EXISTS `ui_notification_logs`;
DROP TABLE IF EXISTS `ui_scheduled_tasks`;
DROP TABLE IF EXISTS `ui_operation_record`;
DROP TABLE IF EXISTS `ui_test_case_executions`;
DROP TABLE IF EXISTS `ui_test_case_steps`;
DROP TABLE IF EXISTS `ui_test_cases`;
DROP TABLE IF EXISTS `ui_screenshots`;
DROP TABLE IF EXISTS `ui_test_environments`;
DROP TABLE IF EXISTS `ui_test_executions`;
DROP TABLE IF EXISTS `ui_test_suite_test_cases`;
DROP TABLE IF EXISTS `ui_test_suite_scripts`;
DROP TABLE IF EXISTS `ui_test_suites`;
DROP TABLE IF EXISTS `ui_script_element_usages`;
DROP TABLE IF EXISTS `ui_script_steps`;
DROP TABLE IF EXISTS `ui_page_object_elements`;
DROP TABLE IF EXISTS `ui_page_objects`;
DROP TABLE IF EXISTS `ui_test_scripts`;
DROP TABLE IF EXISTS `ui_elements`;
DROP TABLE IF EXISTS `ui_element_groups`;
DROP TABLE IF EXISTS `locator_strategies`;
DROP TABLE IF EXISTS `ui_projects`;
DROP TABLE IF EXISTS `api_ai_service_configs`;
DROP TABLE IF EXISTS `api_operation_logs`;
DROP TABLE IF EXISTS `api_task_notification_settings`;
DROP TABLE IF EXISTS `api_notification_logs`;
DROP TABLE IF EXISTS `api_task_execution_logs`;
DROP TABLE IF EXISTS `api_scheduled_tasks`;
DROP TABLE IF EXISTS `api_test_executions`;
DROP TABLE IF EXISTS `api_test_suite_requests`;
DROP TABLE IF EXISTS `api_test_suites`;
DROP TABLE IF EXISTS `api_request_histories`;
DROP TABLE IF EXISTS `api_environments`;
DROP TABLE IF EXISTS `api_requests`;
DROP TABLE IF EXISTS `api_collections`;
DROP TABLE IF EXISTS `api_projects`;
DROP TABLE IF EXISTS `testcase_generation_task`;
DROP TABLE IF EXISTS `generation_config`;
DROP TABLE IF EXISTS `prompt_config`;
DROP TABLE IF EXISTS `ai_model_config`;
DROP TABLE IF EXISTS `analysis_tasks`;
DROP TABLE IF EXISTS `generated_test_cases`;
DROP TABLE IF EXISTS `business_requirements`;
DROP TABLE IF EXISTS `requirement_analyses`;
DROP TABLE IF EXISTS `requirement_documents`;
DROP TABLE IF EXISTS `assistant_messages`;
DROP TABLE IF EXISTS `chat_messages`;
DROP TABLE IF EXISTS `assistant_sessions`;
DROP TABLE IF EXISTS `dify_configs`;
DROP TABLE IF EXISTS `versions`;
DROP TABLE IF EXISTS `review_templates`;
DROP TABLE IF EXISTS `review_comments`;
DROP TABLE IF EXISTS `review_assignments`;
DROP TABLE IF EXISTS `testcase_reviews`;
DROP TABLE IF EXISTS `report_templates`;
DROP TABLE IF EXISTS `test_reports`;
DROP TABLE IF EXISTS `test_run_case_history`;
DROP TABLE IF EXISTS `test_run_cases`;
DROP TABLE IF EXISTS `test_runs`;
DROP TABLE IF EXISTS `test_plans`;
DROP TABLE IF EXISTS `testsuite_cases`;
DROP TABLE IF EXISTS `testsuites`;
DROP TABLE IF EXISTS `testcase_comments`;
DROP TABLE IF EXISTS `testcase_attachments`;
DROP TABLE IF EXISTS `testcase_steps`;
DROP TABLE IF EXISTS `testcases`;
DROP TABLE IF EXISTS `project_environments`;
DROP TABLE IF EXISTS `project_members`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `user_profiles`;
DROP TABLE IF EXISTS `users_user`;
DROP TABLE IF EXISTS `token_blacklist_blacklistedtoken`;
DROP TABLE IF EXISTS `token_blacklist_outstandingtoken`;
DROP TABLE IF EXISTS `authtoken_token`;
DROP TABLE IF EXISTS `django_session`;
DROP TABLE IF EXISTS `django_content_type`;
DROP TABLE IF EXISTS `auth_group`;
DROP TABLE IF EXISTS `auth_permission`;
DROP TABLE IF EXISTS `django_admin_log`;

CREATE TABLE `django_admin_log` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `action_time` datetime(6) NOT NULL, `user_id` bigint NOT NULL, `content_type_id` integer NULL, `object_id` longtext NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint UNSIGNED NOT NULL CHECK (`action_flag` >= 0), `change_message` longtext NOT NULL);
CREATE TABLE `auth_permission` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(255) NOT NULL, `content_type_id` integer NOT NULL, `codename` varchar(100) NOT NULL);
CREATE TABLE `auth_group` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(150) NOT NULL UNIQUE);
CREATE TABLE `auth_group_permissions` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `group_id` integer NOT NULL, `permission_id` integer NOT NULL);
CREATE TABLE `django_content_type` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL);
CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` longtext NOT NULL, `expire_date` datetime(6) NOT NULL);
CREATE TABLE `authtoken_token` (`key` varchar(40) NOT NULL PRIMARY KEY, `user_id` bigint NOT NULL UNIQUE, `created` datetime(6) NOT NULL);
CREATE TABLE `token_blacklist_outstandingtoken` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` bigint NULL, `jti` varchar(255) NOT NULL UNIQUE, `token` longtext NOT NULL, `created_at` datetime(6) NULL, `expires_at` datetime(6) NOT NULL);
CREATE TABLE `token_blacklist_blacklistedtoken` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `token_id` bigint NOT NULL UNIQUE, `blacklisted_at` datetime(6) NOT NULL);
CREATE TABLE `users_user` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `password` varchar(128) NOT NULL, `last_login` datetime(6) NULL, `is_superuser` bool NOT NULL, `username` varchar(150) NOT NULL UNIQUE, `first_name` varchar(150) NOT NULL, `last_name` varchar(150) NOT NULL, `email` varchar(254) NOT NULL, `is_staff` bool NOT NULL, `date_joined` datetime(6) NOT NULL, `avatar` varchar(100) NULL, `phone` varchar(11) NULL, `department` varchar(100) NULL, `position` varchar(100) NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `users_user_groups` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` bigint NOT NULL, `group_id` integer NOT NULL);
CREATE TABLE `users_user_user_permissions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` bigint NOT NULL, `permission_id` integer NOT NULL);
CREATE TABLE `user_profiles` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` bigint NOT NULL UNIQUE, `theme` varchar(20) NOT NULL, `language` varchar(10) NOT NULL, `timezone` varchar(50) NOT NULL, `notifications` json NOT NULL);
CREATE TABLE `projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `status` varchar(20) NOT NULL, `owner_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `project_members` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `user_id` bigint NOT NULL, `role` varchar(20) NOT NULL, `joined_at` datetime(6) NOT NULL);
CREATE TABLE `project_environments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `name` varchar(100) NOT NULL, `base_url` varchar(200) NOT NULL, `description` longtext NOT NULL, `variables` json NOT NULL, `is_default` bool NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `testcases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `title` varchar(500) NOT NULL, `description` longtext NOT NULL, `preconditions` longtext NOT NULL, `steps` longtext NOT NULL, `expected_result` longtext NOT NULL, `priority` varchar(20) NOT NULL, `status` varchar(20) NOT NULL, `test_type` varchar(20) NOT NULL, `tags` json NOT NULL, `author_id` bigint NOT NULL, `assignee_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `testcases_versions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testcase_id` bigint NOT NULL, `version_id` bigint NOT NULL);
CREATE TABLE `testcase_steps` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testcase_id` bigint NOT NULL, `step_number` integer UNSIGNED NOT NULL CHECK (`step_number` >= 0), `action` longtext NOT NULL, `expected` longtext NOT NULL);
CREATE TABLE `testcase_attachments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testcase_id` bigint NOT NULL, `name` varchar(255) NOT NULL, `file` varchar(100) NOT NULL, `uploaded_by_id` bigint NOT NULL, `uploaded_at` datetime(6) NOT NULL);
CREATE TABLE `testcase_comments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testcase_id` bigint NOT NULL, `author_id` bigint NOT NULL, `content` longtext NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `testsuites` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `author_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `testsuite_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testsuite_id` bigint NOT NULL, `testcase_id` bigint NOT NULL, `order` integer UNSIGNED NOT NULL CHECK (`order` >= 0));
CREATE TABLE `test_plans` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `version_id` bigint NULL, `creator_id` bigint NOT NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `test_plans_projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testplan_id` bigint NOT NULL, `project_id` bigint NOT NULL);
CREATE TABLE `test_plans_assignees` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testplan_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `test_runs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `test_plan_id` bigint NOT NULL, `project_id` bigint NOT NULL, `version_id` bigint NULL, `assignee_id` bigint NOT NULL, `creator_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `started_at` datetime(6) NULL, `completed_at` datetime(6) NULL, `due_date` datetime(6) NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `test_run_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_run_id` bigint NOT NULL, `testcase_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `priority` varchar(20) NOT NULL, `actual_result` longtext NOT NULL, `comments` longtext NOT NULL, `defects` json NOT NULL, `elapsed_time` bigint NULL, `executed_by_id` bigint NULL, `executed_at` datetime(6) NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `test_run_case_history` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `run_case_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `actual_result` longtext NOT NULL, `comments` longtext NOT NULL, `executed_by_id` bigint NOT NULL, `executed_at` datetime(6) NOT NULL);
CREATE TABLE `test_reports` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `name` varchar(200) NOT NULL, `report_type` varchar(20) NOT NULL, `execution_id` bigint NULL UNIQUE, `summary` json NOT NULL, `content` json NOT NULL, `generated_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `report_templates` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `template_config` json NOT NULL, `is_default` bool NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `testcase_reviews` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(500) NOT NULL, `description` longtext NOT NULL, `creator_id` bigint NOT NULL, `template_id` bigint NULL, `status` varchar(20) NOT NULL, `priority` varchar(20) NOT NULL, `deadline` datetime(6) NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `completed_at` datetime(6) NULL);
CREATE TABLE `testcase_reviews_projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testcasereview_id` bigint NOT NULL, `project_id` bigint NOT NULL);
CREATE TABLE `testcase_reviews_testcases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `testcasereview_id` bigint NOT NULL, `testcase_id` bigint NOT NULL);
CREATE TABLE `review_assignments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `review_id` bigint NOT NULL, `reviewer_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `comment` longtext NOT NULL, `checklist_results` json NOT NULL, `reviewed_at` datetime(6) NULL, `assigned_at` datetime(6) NOT NULL);
CREATE TABLE `review_comments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `review_id` bigint NOT NULL, `testcase_id` bigint NULL, `author_id` bigint NOT NULL, `comment_type` varchar(20) NOT NULL, `content` longtext NOT NULL, `step_number` integer UNSIGNED NULL CHECK (`step_number` >= 0), `is_resolved` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `review_templates` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `creator_id` bigint NOT NULL, `checklist` json NOT NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `review_templates_project` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `reviewtemplate_id` bigint NOT NULL, `project_id` bigint NOT NULL);
CREATE TABLE `review_templates_default_reviewers` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `reviewtemplate_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `versions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `description` longtext NOT NULL, `is_baseline` bool NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `versions_projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `version_id` bigint NOT NULL, `project_id` bigint NOT NULL);
CREATE TABLE `dify_configs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `api_url` varchar(500) NOT NULL, `api_key` varchar(500) NOT NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `assistant_sessions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` bigint NOT NULL, `session_id` varchar(200) NOT NULL, `conversation_id` varchar(200) NULL, `title` varchar(500) NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `chat_messages` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `session_id` bigint NOT NULL, `role` varchar(20) NOT NULL, `content` longtext NOT NULL, `conversation_id` varchar(200) NULL, `message_id` varchar(200) NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `assistant_messages` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `session_id` bigint NOT NULL, `message_type` varchar(20) NOT NULL, `content` longtext NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `requirement_documents` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `title` varchar(200) NOT NULL, `file` varchar(100) NOT NULL, `document_type` varchar(10) NOT NULL, `status` varchar(20) NOT NULL, `uploaded_by_id` bigint NOT NULL, `project_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `file_size` integer UNSIGNED NULL CHECK (`file_size` >= 0), `extracted_text` longtext NOT NULL);
CREATE TABLE `requirement_analyses` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `document_id` bigint NOT NULL UNIQUE, `analysis_report` longtext NOT NULL, `requirements_count` integer UNSIGNED NOT NULL CHECK (`requirements_count` >= 0), `analysis_time` double precision NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `business_requirements` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `analysis_id` bigint NOT NULL, `requirement_id` varchar(50) NOT NULL, `requirement_name` varchar(200) NOT NULL, `requirement_type` varchar(20) NOT NULL, `parent_requirement_id` bigint NULL, `module` varchar(100) NOT NULL, `requirement_level` varchar(10) NOT NULL, `reviewer` varchar(50) NOT NULL, `estimated_hours` integer UNSIGNED NOT NULL CHECK (`estimated_hours` >= 0), `description` longtext NOT NULL, `acceptance_criteria` longtext NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `generated_test_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `requirement_id` bigint NOT NULL, `case_id` varchar(50) NOT NULL, `title` varchar(300) NOT NULL, `priority` varchar(5) NOT NULL, `precondition` longtext NOT NULL, `test_steps` longtext NOT NULL, `expected_result` longtext NOT NULL, `status` varchar(20) NOT NULL, `generated_by_ai` varchar(50) NOT NULL, `reviewed_by_ai` varchar(50) NULL, `review_comments` longtext NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `analysis_tasks` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` varchar(100) NOT NULL UNIQUE, `task_type` varchar(30) NOT NULL, `document_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `progress` integer UNSIGNED NOT NULL CHECK (`progress` >= 0), `result` json NULL, `error_message` longtext NOT NULL, `started_at` datetime(6) NULL, `completed_at` datetime(6) NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ai_model_config` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `model_type` varchar(20) NOT NULL, `api_key` varchar(200) NULL, `base_url` varchar(200) NOT NULL, `model_name` varchar(100) NOT NULL, `max_tokens` integer NOT NULL, `temperature` double precision NOT NULL, `top_p` double precision NOT NULL, `is_active` bool NOT NULL, `is_builtin` bool NOT NULL, `speed_ms` integer NOT NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `prompt_config` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `prompt_type` varchar(20) NOT NULL, `content` longtext NOT NULL, `is_active` bool NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `generation_config` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `default_output_mode` varchar(10) NOT NULL, `enable_auto_review` bool NOT NULL, `review_timeout` integer NOT NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `testcase_generation_task` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` varchar(50) NOT NULL UNIQUE, `title` varchar(200) NOT NULL, `requirement_text` longtext NOT NULL, `status` varchar(20) NOT NULL, `progress` integer NOT NULL, `output_mode` varchar(10) NOT NULL, `stream_buffer` longtext NOT NULL, `stream_position` integer NOT NULL, `last_stream_update` datetime(6) NULL, `project_id` bigint NULL, `writer_model_config_id` bigint NULL, `reviewer_model_config_id` bigint NULL, `writer_prompt_config_id` bigint NULL, `reviewer_prompt_config_id` bigint NULL, `generated_test_cases` longtext NOT NULL, `review_feedback` longtext NOT NULL, `final_test_cases` longtext NOT NULL, `target_url` varchar(500) NOT NULL, `generation_log` longtext NOT NULL, `error_message` longtext NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `completed_at` datetime(6) NULL, `is_saved_to_records` bool NOT NULL, `saved_at` datetime(6) NULL, `workflow_stage` varchar(20) NOT NULL, `reviewer_notes` longtext NOT NULL, `approver_notes` longtext NOT NULL, `approved_at` datetime(6) NULL, `rejected_at` datetime(6) NULL, `executed_at` datetime(6) NULL);
CREATE TABLE `api_projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `project_type` varchar(20) NOT NULL, `status` varchar(20) NOT NULL, `start_date` date NULL, `end_date` date NULL, `owner_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_projects_members` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `apiproject_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `api_collections` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `order` integer NOT NULL, `project_id` bigint NOT NULL, `parent_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_requests` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `collection_id` bigint NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `request_type` varchar(20) NOT NULL, `method` varchar(10) NOT NULL, `url` longtext NOT NULL, `headers` json NOT NULL, `params` json NOT NULL, `body` json NOT NULL, `auth` json NOT NULL, `pre_request_script` longtext NOT NULL, `post_request_script` longtext NOT NULL, `assertions` json NOT NULL, `order` integer NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_environments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `scope` varchar(10) NOT NULL, `variables` json NOT NULL, `is_active` bool NOT NULL, `project_id` bigint NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_request_histories` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `request_id` bigint NOT NULL, `environment_id` bigint NULL, `request_data` json NOT NULL, `response_data` json NULL, `status_code` integer NULL, `response_time` double precision NULL, `error_message` longtext NOT NULL, `assertions_results` json NULL, `executed_by_id` bigint NOT NULL, `executed_at` datetime(6) NOT NULL);
CREATE TABLE `api_test_suites` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `environment_id` bigint NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_test_suite_requests` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_suite_id` bigint NOT NULL, `request_id` bigint NOT NULL, `order` integer NOT NULL, `assertions` json NOT NULL, `enabled` bool NOT NULL);
CREATE TABLE `api_test_executions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_suite_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `start_time` datetime(6) NULL, `end_time` datetime(6) NULL, `total_requests` integer NOT NULL, `passed_requests` integer NOT NULL, `failed_requests` integer NOT NULL, `results` json NOT NULL, `executed_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `api_scheduled_tasks` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `task_type` varchar(20) NOT NULL, `trigger_type` varchar(20) NOT NULL, `cron_expression` varchar(100) NOT NULL, `interval_seconds` integer NULL, `execute_at` datetime(6) NULL, `test_suite_id` bigint NULL, `api_request_id` bigint NULL, `environment_id` bigint NULL, `status` varchar(20) NOT NULL, `last_run_time` datetime(6) NULL, `next_run_time` datetime(6) NULL, `total_runs` integer NOT NULL, `successful_runs` integer NOT NULL, `failed_runs` integer NOT NULL, `last_result` json NOT NULL, `error_message` longtext NOT NULL, `notify_on_success` bool NOT NULL, `notify_on_failure` bool NOT NULL, `notify_emails` json NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_task_execution_logs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `start_time` datetime(6) NULL, `end_time` datetime(6) NULL, `duration` double precision NULL, `result` json NOT NULL, `error_message` longtext NOT NULL, `executed_by_id` bigint NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `api_notification_logs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` bigint NULL, `task_name` varchar(200) NOT NULL, `task_type` varchar(20) NULL, `notification_type` varchar(50) NOT NULL, `sender_name` varchar(100) NOT NULL, `sender_email` varchar(254) NOT NULL, `recipient_info` json NOT NULL, `webhook_bot_info` json NULL, `notification_content` longtext NOT NULL, `status` varchar(20) NOT NULL, `error_message` longtext NULL, `response_info` json NULL, `created_at` datetime(6) NOT NULL, `sent_at` datetime(6) NULL, `retry_count` integer NOT NULL, `is_retried` bool NOT NULL);
CREATE TABLE `api_task_notification_settings` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` bigint NOT NULL, `notification_type` varchar(20) NOT NULL, `notification_config_id` bigint NULL, `is_enabled` bool NOT NULL, `notify_on_success` bool NOT NULL, `notify_on_failure` bool NOT NULL, `notify_on_timeout` bool NOT NULL, `notify_on_error` bool NOT NULL, `custom_webhook_bots` json NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `api_task_notification_settings_custom_recipients` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `tasknotificationsetting_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `api_operation_logs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `operation_type` varchar(20) NOT NULL, `resource_type` varchar(20) NOT NULL, `resource_id` integer NOT NULL, `resource_name` varchar(200) NOT NULL, `description` longtext NOT NULL, `user_id` bigint NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `api_ai_service_configs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `service_type` varchar(20) NOT NULL, `role` varchar(20) NOT NULL, `api_key` varchar(500) NOT NULL, `base_url` varchar(500) NOT NULL, `model_name` varchar(200) NOT NULL, `max_tokens` integer NOT NULL, `temperature` double precision NOT NULL, `is_active` bool NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `status` varchar(20) NOT NULL, `base_url` varchar(200) NOT NULL, `start_date` date NULL, `end_date` date NULL, `owner_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_projects_members` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `uiproject_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `locator_strategies` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(50) NOT NULL, `description` longtext NOT NULL);
CREATE TABLE `ui_element_groups` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `project_id` bigint NOT NULL, `parent_group_id` bigint NULL, `order` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_elements` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `group_id` bigint NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `element_type` varchar(50) NOT NULL, `locator_strategy_id` bigint NOT NULL, `locator_value` varchar(500) NOT NULL, `backup_locators` json NULL, `page` varchar(200) NOT NULL, `component_name` varchar(100) NOT NULL, `parent_element_id` bigint NULL, `is_unique` bool NOT NULL, `wait_timeout` integer NOT NULL, `is_visible` bool NOT NULL, `is_enabled` bool NOT NULL, `force_action` bool NOT NULL, `usage_count` integer NOT NULL, `last_validated` datetime(6) NULL, `validation_status` varchar(20) NOT NULL, `validation_message` longtext NOT NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_scripts` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `script_type` varchar(20) NOT NULL, `content` longtext NOT NULL, `language` varchar(20) NOT NULL, `framework` varchar(20) NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_page_objects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `class_name` varchar(200) NOT NULL, `url_pattern` varchar(500) NOT NULL, `project_id` bigint NOT NULL, `description` longtext NOT NULL, `template_code` longtext NOT NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_page_object_elements` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `page_object_id` bigint NOT NULL, `element_id` bigint NOT NULL, `method_name` varchar(100) NOT NULL, `is_property` bool NOT NULL, `order` integer NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_script_steps` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `script_id` bigint NOT NULL, `step_order` integer NOT NULL, `action_type` varchar(20) NOT NULL, `target_element_id` bigint NULL, `page_object_id` bigint NULL, `action_params` json NULL, `description` varchar(500) NOT NULL, `expected_result` varchar(500) NOT NULL, `wait_before` integer NOT NULL, `wait_after` integer NOT NULL, `retry_count` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_script_element_usages` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `script_id` bigint NOT NULL, `element_id` bigint NOT NULL, `usage_type` varchar(50) NOT NULL, `line_number` integer NOT NULL, `context` longtext NOT NULL, `frequency` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_suites` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `execution_status` varchar(20) NOT NULL, `passed_count` integer NOT NULL, `failed_count` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_suite_scripts` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_suite_id` bigint NOT NULL, `test_script_id` bigint NOT NULL, `order` integer NOT NULL);
CREATE TABLE `ui_test_suite_test_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_suite_id` bigint NOT NULL, `test_case_id` bigint NOT NULL, `order` integer NOT NULL);
CREATE TABLE `ui_test_executions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NOT NULL, `test_suite_id` bigint NULL, `test_script_id` bigint NULL, `environment` varchar(20) NOT NULL, `status` varchar(20) NOT NULL, `total_cases` integer NOT NULL, `passed_cases` integer NOT NULL, `failed_cases` integer NOT NULL, `skipped_cases` integer NOT NULL, `started_at` datetime(6) NULL, `finished_at` datetime(6) NULL, `duration` double precision NOT NULL, `executed_by_id` bigint NULL, `engine` varchar(20) NOT NULL, `browser` varchar(20) NOT NULL, `headless` bool NOT NULL, `result_data` json NULL, `error_message` longtext NOT NULL, `report_url` varchar(500) NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_environments` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `description` longtext NOT NULL, `browser_type` varchar(50) NOT NULL, `browser_version` varchar(50) NOT NULL, `resolution` varchar(50) NOT NULL, `os_type` varchar(50) NOT NULL, `os_version` varchar(50) NOT NULL, `capabilities` json NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_screenshots` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `execution_id` bigint NOT NULL, `name` varchar(200) NOT NULL, `image` varchar(100) NOT NULL, `description` longtext NOT NULL, `captured_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `project_id` bigint NOT NULL, `status` varchar(20) NOT NULL, `priority` varchar(10) NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_case_steps` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_case_id` bigint NOT NULL, `step_number` integer NOT NULL, `action_type` varchar(20) NOT NULL, `element_id` bigint NULL, `input_value` longtext NOT NULL, `wait_time` integer NOT NULL, `assert_type` varchar(20) NOT NULL, `assert_value` longtext NOT NULL, `description` longtext NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_test_case_executions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_case_id` bigint NOT NULL, `project_id` bigint NOT NULL, `test_suite_id` bigint NULL, `execution_source` varchar(20) NOT NULL, `status` varchar(20) NOT NULL, `engine` varchar(20) NOT NULL, `browser` varchar(50) NOT NULL, `headless` bool NOT NULL, `execution_logs` longtext NOT NULL, `error_message` longtext NULL, `screenshots` json NOT NULL, `execution_time` double precision NULL, `started_at` datetime(6) NULL, `finished_at` datetime(6) NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_operation_record` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `operation_type` varchar(20) NOT NULL, `resource_type` varchar(20) NOT NULL, `resource_id` integer NOT NULL, `resource_name` varchar(200) NOT NULL, `description` longtext NOT NULL, `user_id` bigint NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_scheduled_tasks` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `task_type` varchar(20) NOT NULL, `trigger_type` varchar(20) NOT NULL, `cron_expression` varchar(100) NOT NULL, `interval_seconds` integer NULL, `execute_at` datetime(6) NULL, `project_id` bigint NOT NULL, `test_suite_id` bigint NULL, `test_cases` json NOT NULL, `engine` varchar(20) NOT NULL, `browser` varchar(20) NOT NULL, `headless` bool NOT NULL, `notify_on_success` bool NOT NULL, `notify_on_failure` bool NOT NULL, `notification_type` varchar(20) NOT NULL, `notify_emails` json NOT NULL, `status` varchar(20) NOT NULL, `last_run_time` datetime(6) NULL, `next_run_time` datetime(6) NULL, `total_runs` integer NOT NULL, `successful_runs` integer NOT NULL, `failed_runs` integer NOT NULL, `last_result` json NOT NULL, `error_message` longtext NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_notification_logs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` bigint NULL, `task_name` varchar(200) NOT NULL, `task_type` varchar(20) NULL, `notification_type` varchar(50) NOT NULL, `sender_name` varchar(100) NOT NULL, `sender_email` varchar(254) NOT NULL, `recipient_info` json NOT NULL, `webhook_bot_info` json NULL, `notification_content` longtext NOT NULL, `status` varchar(20) NOT NULL, `error_message` longtext NULL, `response_info` json NULL, `created_at` datetime(6) NOT NULL, `sent_at` datetime(6) NULL, `retry_count` integer NOT NULL, `is_retried` bool NOT NULL);
CREATE TABLE `ui_task_notification_settings` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` bigint NOT NULL, `notification_type` varchar(20) NOT NULL, `notification_config_id` bigint NULL, `is_enabled` bool NOT NULL, `notify_on_success` bool NOT NULL, `notify_on_failure` bool NOT NULL, `notify_on_timeout` bool NOT NULL, `notify_on_error` bool NOT NULL, `custom_webhook_bots` json NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `ui_task_notification_settings_custom_recipients` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `uitasknotificationsetting_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `ui_ai_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NULL, `name` varchar(200) NOT NULL, `description` longtext NULL, `task_description` longtext NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `created_by_id` bigint NULL);
CREATE TABLE `ui_ai_execution_records` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NULL, `ai_case_id` bigint NULL, `case_name` varchar(200) NOT NULL, `task_description` longtext NOT NULL, `execution_mode` varchar(20) NOT NULL, `status` varchar(20) NOT NULL, `start_time` datetime(6) NOT NULL, `end_time` datetime(6) NULL, `duration` double precision NULL, `logs` longtext NOT NULL, `steps_completed` json NOT NULL, `planned_tasks` json NOT NULL, `executed_by_id` bigint NULL, `gif_path` varchar(500) NULL, `screenshots_sequence` json NOT NULL);
CREATE TABLE `automation_executions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` varchar(100) NOT NULL UNIQUE, `case_name` varchar(200) NOT NULL, `description` longtext NOT NULL, `source_type` varchar(20) NOT NULL, `source_id` varchar(100) NULL, `project_id` bigint NULL, `generated_testcase_id` bigint NULL, `status` varchar(20) NOT NULL, `execution_mode` varchar(20) NOT NULL, `current_step_index` integer NOT NULL, `current_case_index` integer NOT NULL, `last_executed_step_id` varchar(100) NULL, `target_url` varchar(1000) NOT NULL, `browser_type` varchar(20) NOT NULL, `headless` bool NOT NULL, `timeout` integer NOT NULL, `steps_definition` json NULL, `artifact_dir` varchar(500) NOT NULL, `video_path` varchar(500) NOT NULL, `report_path` varchar(500) NOT NULL, `trace_path` varchar(500) NOT NULL, `har_path` varchar(500) NOT NULL, `total_cases` integer NOT NULL, `passed_cases` integer NOT NULL, `failed_cases` integer NOT NULL, `blocked_cases` integer NOT NULL, `total_steps` integer NOT NULL, `passed_steps` integer NOT NULL, `failed_steps` integer NOT NULL, `duration` double precision NULL, `error_message` longtext NOT NULL, `blocking_reason` longtext NOT NULL, `created_by_id` bigint NOT NULL, `executed_by_id` bigint NULL, `started_at` datetime(6) NULL, `completed_at` datetime(6) NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `can_resume` bool NOT NULL, `resume_data` json NULL, `celery_task_id` varchar(100) NOT NULL);
CREATE TABLE `ui_execution_steps` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `execution_id` bigint NOT NULL, `step_id` varchar(100) NOT NULL, `step_name` varchar(200) NOT NULL, `step_desc` longtext NOT NULL, `step_index` integer NOT NULL, `action_type` varchar(50) NOT NULL, `status` varchar(20) NOT NULL, `started_at` datetime(6) NULL, `completed_at` datetime(6) NULL, `duration` double precision NULL, `url` varchar(1000) NOT NULL, `page_title` varchar(500) NOT NULL, `screenshot_before` varchar(500) NOT NULL, `screenshot_after` varchar(500) NOT NULL, `error_message` longtext NOT NULL, `dom_path` varchar(500) NOT NULL, `console_log_path` varchar(500) NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_execution_evidences` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `execution_id` bigint NOT NULL, `step_id` bigint NULL, `evidence_type` varchar(20) NOT NULL, `file_path` varchar(500) NOT NULL, `file_name` varchar(200) NOT NULL, `description` varchar(500) NOT NULL, `created_at` datetime(6) NOT NULL);
CREATE TABLE `ui_execution_logs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `execution_id` bigint NOT NULL, `step_id` bigint NULL, `log_level` varchar(20) NOT NULL, `message` longtext NOT NULL, `timestamp` datetime(6) NOT NULL);
CREATE TABLE `app_projects` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `status` varchar(20) NOT NULL, `start_date` date NULL, `end_date` date NULL, `owner_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_projects_members` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `appproject_id` bigint NOT NULL, `user_id` bigint NOT NULL);
CREATE TABLE `app_test_config` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `adb_path` varchar(500) NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_devices` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `device_id` varchar(255) NOT NULL UNIQUE, `name` varchar(255) NOT NULL, `status` varchar(20) NOT NULL, `android_version` varchar(50) NOT NULL, `connection_type` varchar(20) NOT NULL, `ip_address` varchar(50) NOT NULL, `port` integer NOT NULL, `locked_by_id` bigint NULL, `locked_at` datetime(6) NULL, `max_allocation_time` integer NOT NULL, `device_specs` json NOT NULL, `description` longtext NOT NULL, `location` varchar(200) NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_elements` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NULL, `name` varchar(200) NOT NULL UNIQUE, `element_type` varchar(10) NOT NULL, `tags` json NOT NULL, `config` json NOT NULL, `resolution_configs` json NOT NULL, `usage_count` integer NOT NULL, `last_used_at` datetime(6) NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `is_active` bool NOT NULL);
CREATE TABLE `app_components` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `type` varchar(50) NOT NULL UNIQUE, `category` varchar(50) NOT NULL, `description` longtext NOT NULL, `schema` json NOT NULL, `default_config` json NOT NULL, `enabled` bool NOT NULL, `sort_order` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_custom_components` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `type` varchar(50) NOT NULL UNIQUE, `description` longtext NOT NULL, `schema` json NOT NULL, `default_config` json NOT NULL, `steps` json NOT NULL, `enabled` bool NOT NULL, `sort_order` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_component_packages` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `version` varchar(50) NOT NULL, `description` longtext NOT NULL, `author` varchar(100) NOT NULL, `source` varchar(20) NOT NULL, `manifest` json NOT NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_packages` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `package_name` varchar(255) NOT NULL UNIQUE, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_test_suites` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `execution_status` varchar(20) NOT NULL, `execution_result` varchar(20) NULL, `passed_count` integer NOT NULL, `failed_count` integer NOT NULL, `last_run_at` datetime(6) NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_test_suite_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_suite_id` bigint NOT NULL, `test_case_id` bigint NOT NULL, `order` integer NOT NULL);
CREATE TABLE `app_test_cases` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `app_package_id` bigint NULL, `ui_flow` json NOT NULL, `variables` json NOT NULL, `timeout` integer NOT NULL, `retry_count` integer NOT NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_test_executions` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `test_case_id` bigint NULL, `test_suite_id` bigint NULL, `device_id` bigint NULL, `user_id` bigint NULL, `status` varchar(20) NOT NULL, `result` varchar(20) NULL, `task_id` varchar(255) NOT NULL, `progress` integer NOT NULL, `started_at` datetime(6) NULL, `finished_at` datetime(6) NULL, `duration` double precision NOT NULL, `report_path` varchar(500) NOT NULL, `error_message` longtext NOT NULL, `total_steps` integer NOT NULL, `passed_steps` integer NOT NULL, `failed_steps` integer NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_scheduled_tasks` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `project_id` bigint NULL, `name` varchar(200) NOT NULL, `description` longtext NOT NULL, `task_type` varchar(20) NOT NULL, `trigger_type` varchar(20) NOT NULL, `cron_expression` varchar(100) NOT NULL, `interval_seconds` integer NULL, `execute_at` datetime(6) NULL, `device_id` bigint NULL, `app_package_id` bigint NULL, `test_suite_id` bigint NULL, `test_case_id` bigint NULL, `notify_on_success` bool NOT NULL, `notify_on_failure` bool NOT NULL, `notification_type` varchar(20) NOT NULL, `notify_emails` json NOT NULL, `status` varchar(20) NOT NULL, `last_run_time` datetime(6) NULL, `next_run_time` datetime(6) NULL, `total_runs` integer NOT NULL, `successful_runs` integer NOT NULL, `failed_runs` integer NOT NULL, `last_result` json NOT NULL, `error_message` longtext NOT NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `app_notification_logs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `task_id` bigint NULL, `task_name` varchar(200) NOT NULL, `task_type` varchar(20) NOT NULL, `notification_type` varchar(50) NOT NULL, `sender_name` varchar(100) NOT NULL, `sender_email` varchar(254) NOT NULL, `recipient_info` json NOT NULL, `webhook_bot_info` json NOT NULL, `notification_content` longtext NOT NULL, `status` varchar(20) NOT NULL, `error_message` longtext NOT NULL, `response_info` json NOT NULL, `created_at` datetime(6) NOT NULL, `sent_at` datetime(6) NULL, `retry_count` integer NOT NULL, `is_retried` bool NOT NULL);
CREATE TABLE `app_virtual_devices` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `device_id` varchar(255) NOT NULL UNIQUE, `name` varchar(200) NOT NULL, `status` varchar(20) NOT NULL, `brand` varchar(50) NOT NULL, `model` varchar(100) NOT NULL, `android_version` varchar(50) NOT NULL, `api_level` integer NOT NULL, `cpu` varchar(100) NOT NULL, `ram_gb` integer NOT NULL, `storage_gb` integer NOT NULL, `screen_resolution` varchar(50) NOT NULL, `screen_density` varchar(50) NOT NULL, `network_type` varchar(20) NOT NULL, `download_speed_mbps` integer NOT NULL, `upload_speed_mbps` integer NOT NULL, `latency_ms` integer NOT NULL, `emulator_path` varchar(500) NOT NULL, `port` integer NOT NULL, `system_image_path` varchar(500) NOT NULL, `extra_config` json NOT NULL, `created_by_id` bigint NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `started_at` datetime(6) NULL);
CREATE TABLE `app_virtual_device_pool` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `device_id` bigint NOT NULL UNIQUE, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `unified_notification_configs` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `name` varchar(100) NOT NULL, `config_type` varchar(20) NOT NULL, `webhook_bots` json NULL, `is_default` bool NOT NULL, `is_active` bool NOT NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL, `created_by_id` bigint NOT NULL);
CREATE TABLE `data_factory_record` (`id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` bigint NOT NULL, `tool_name` varchar(100) NOT NULL, `tool_category` varchar(20) NOT NULL, `tool_scenario` varchar(20) NOT NULL, `input_data` json NULL, `output_data` json NOT NULL, `is_saved` bool NOT NULL, `tags` json NULL, `created_at` datetime(6) NOT NULL, `updated_at` datetime(6) NOT NULL);
CREATE TABLE `performance_load_test_tasks` (`id` char(32) NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `test_type` varchar(20) NOT NULL, `target_url` varchar(500) NOT NULL, `concurrency` integer NOT NULL, `duration` integer NOT NULL, `ramp_up` integer NOT NULL, `status` varchar(20) NOT NULL, `peak_rps` double precision NOT NULL, `avg_response_time` double precision NOT NULL, `error_rate` double precision NOT NULL, `total_requests` integer NOT NULL, `result_summary` longtext NOT NULL, `report_file` varchar(100) NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `started_at` datetime(6) NULL, `completed_at` datetime(6) NULL);
CREATE TABLE `security_scan_tasks` (`id` char(32) NOT NULL PRIMARY KEY, `name` varchar(200) NOT NULL, `scan_type` varchar(20) NOT NULL, `target` varchar(500) NOT NULL, `tool` varchar(50) NOT NULL, `depth` integer NOT NULL, `status` varchar(20) NOT NULL, `total_risks` integer NOT NULL, `high_risks` integer NOT NULL, `medium_risks` integer NOT NULL, `low_risks` integer NOT NULL, `result_summary` longtext NOT NULL, `report_file` varchar(100) NULL, `created_by_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL, `started_at` datetime(6) NULL, `completed_at` datetime(6) NULL);
CREATE TABLE `security_findings` (`id` char(32) NOT NULL PRIMARY KEY, `task_id` char(32) NOT NULL, `title` varchar(300) NOT NULL, `detail` longtext NOT NULL, `severity` varchar(20) NOT NULL, `target` varchar(500) NOT NULL, `remediation` longtext NOT NULL, `created_at` datetime(6) NOT NULL);

CREATE TABLE `django_migrations` (
  `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `app` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `applied` datetime(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('contenttypes', '0002_remove_content_type_name', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0002_alter_permission_name_max_length', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0003_alter_user_email_max_length', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0004_alter_user_username_opts', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0005_alter_user_last_login_null', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0006_require_contenttypes_0002', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0007_alter_validators_add_error_messages', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0008_alter_user_username_max_length', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0009_alter_user_last_name_max_length', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0010_alter_group_name_max_length', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0011_update_proxy_permissions', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('auth', '0012_alter_user_first_name_max_length', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('users', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0002_logentry_remove_auto_add', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('admin', '0003_logentry_add_action_flag_choices', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('core', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('api_testing', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('api_testing', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('app_automation', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('app_automation', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('app_automation', '0003_add_virtual_devices', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('assistant', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('assistant', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('authtoken', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('authtoken', '0002_auto_20160226_1747', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('authtoken', '0003_tokenproxy', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('authtoken', '0004_alter_tokenproxy_options', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('core', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('data_factory', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('data_factory', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('projects', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('versions', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('testcases', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('executions', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('executions', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('performance_testing', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('projects', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('reports', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('reports', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0003_add_target_url', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0004_alter_aimodelconfig_role', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0005_add_workflow_stage', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0006_add_is_builtin_and_speed_ms', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('requirement_analysis', '0007_make_created_by_nullable', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('reviews', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('reviews', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('security_testing', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('sessions', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('testcases', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('testsuites', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('testsuites', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0002_outstandingtoken_jti_hex', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0003_auto_20171017_2007', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0004_auto_20171017_2013', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0005_remove_outstandingtoken_jti', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0006_auto_20171017_2113', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0007_auto_20171017_2214', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0008_migrate_to_bigautofield', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0010_fix_migrate_to_bigautofield', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0011_linearizes_history', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0012_alter_outstandingtoken_user', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('ui_automation', '0001_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('ui_automation', '0002_initial', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('ui_automation', '0003_aiexecutionrecord_generated_test_cases_and_more', NOW(6));
INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('ui_automation', '0004_remove_aiexecutionrecord_generated_test_cases_and_more', NOW(6));

INSERT INTO `users_user` (`id`, `password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`, `created_at`, `updated_at`) 
VALUES (1, '!', NULL, 1, 'zxplatform', 'Admin', 'ZXAItext', 'admin@zxaitext.com', 1, 1, NOW(6), NOW(6), NOW(6));

INSERT INTO `ai_model_config` (`name`, `model_type`, `api_key`, `base_url`, `model_name`, `max_tokens`, `temperature`, `top_p`, `is_active`, `is_builtin`, `speed_ms`, `created_by_id`, `created_at`, `updated_at`) VALUES
('Agnes AI（内置默认）', 'other', 'sk-7qYB71TuZ2BZEBDPUN5Y3r9QEP7YRij4NgDiQpmNGfOzr7ZE', 'https://apihub.agnes-ai.com/v1', 'agnes-2.0-flash', 4096, 0.7, 0.9, 1, 1, 0, 1, NOW(6), NOW(6));

INSERT INTO `prompt_config` (`name`, `prompt_type`, `content`, `is_active`, `created_by_id`, `created_at`, `updated_at`) VALUES
('默认测试用例编写提示词', 'writer', '你是一位拥有30年经验的资深测试用例编写专家，精通软件测试理论、测试设计方法和质量保障体系。\n\n【职责定位】\n根据业务需求文档，设计高质量、可执行、覆盖全面的测试用例，确保产品质量。\n\n【测试用例设计原则】\n1. **等价类划分**：合理划分有效等价类和无效等价类，确保数据覆盖全面\n2. **边界值分析**：重点测试边界条件和临界值\n3. **因果图法**：分析输入输出之间的因果关系\n4. **场景法**：覆盖正常、异常、边界等各种业务场景\n5. **正交试验**：用最少用例覆盖最大测试范围\n\n【用例结构规范】\n每条测试用例必须包含：\n- 用例ID：唯一标识\n- 测试标题：简洁描述测试目标\n- 前置条件：执行测试前必须满足的条件\n- 测试步骤：详细的操作步骤（Step by Step）\n- 预期结果：明确、可验证的预期行为\n- 优先级：P0（致命）/P1（严重）/P2（一般）/P3（轻微）\n\n【覆盖维度】\n- 功能正向测试\n- 异常流程测试\n- 边界值测试\n- 数据完整性测试\n- 业务规则验证\n- 兼容性测试\n- 性能基准测试\n- 安全性测试\n\n【输出要求】\n请严格按照JSON格式输出测试用例数组，确保格式正确、数据完整。', 1, 1, NOW(6), NOW(6)),
('默认测试用例评审提示词', 'reviewer', '你是一名资深测试架构师（Test Architect），拥有极高的质量标准和丰富的测试评审经验。\n\n【职责定位】\n对测试用例进行严格、专业的评审，确保用例质量达到企业级标准。\n\n【评审标准】\n\n一、覆盖率评估（30分）\n- 是否覆盖所有功能点\n- 是否覆盖异常场景\n- 是否覆盖边界条件\n- 是否覆盖业务规则\n\n二、正确性评估（25分）\n- 前置条件是否充分\n- 测试步骤是否正确\n- 预期结果是否明确可验证\n- 是否存在逻辑错误\n\n三、可执行性评估（20分）\n- 步骤描述是否清晰\n- 是否存在歧义\n- 是否可以独立执行\n- 是否需要额外说明\n\n四、规范性评估（15分）\n- 用例标题是否清晰\n- 优先级是否合理\n- 格式是否规范\n- 是否存在重复用例\n\n五、可维护性评估（10分）\n- 是否易于理解\n- 是否易于修改\n- 是否便于回归\n- 是否符合命名规范\n\n【评审输出】\n输出JSON格式，包含：\n- overall_score：总体评分（0-100）\n- pass_rate：通过率\n- reviewed_cases：每条用例的评审详情（test_case_id, review_score, review_comments, status）\n- summary：总体评价和改进建议', 1, 1, NOW(6), NOW(6));

INSERT INTO `generation_config` (`name`, `default_output_mode`, `enable_auto_review`, `review_timeout`, `is_active`, `created_at`, `updated_at`) VALUES
('默认生成配置', 'stream', 1, 120, 1, NOW(6), NOW(6));

SET FOREIGN_KEY_CHECKS = 1;
